services:
  backend:
    build:
      context: ./fv-backend
    ports:
      - "3000:3000"
    env_file:
      - ./fv-backend/.env
    environment:
      - CORS_ORIGIN=http://localhost:4200

  frontend:
    build:
      context: ./fv-frontend
      args:
        API_URL: http://localhost:3000
    ports:
      - "8080:80"
    depends_on:
      - backend
